{
    'name': 'PetaDigi',
    'version': '1.0.0',
    'summary': 'Module for Digital Map.',
    'description': 'Digital map module for Odoo, providing interactive mapping features and geolocation services.',
    'category': 'Tools',
    'author': 'Sel Studio',
    'website': 'https://selstudio.id',
    'depends': ['base', 'web'],
    'data': [
        'security/ir.model.access.csv', 
        'views/polres_views.xml',
        'views/polsek_views.xml',
        'views/kabupaten_views.xml',
        'views/kecamatan_views.xml',
        'views/desa_views.xml',
        'views/sumber_dokumen_views.xml',
        'views/kategori_kriminal_views.xml',
        'views/sub_kategori_kriminal_views.xml',
        'views/kategori_bencana_views.xml',
        'views/kategori_kamtibmas_views.xml',
        'views/kategori_lalu_lintas_views.xml',
        'views/kategori_lokasi_views.xml',
        'views/jenis_jalan_views.xml',
        'views/modus_operandi_views.xml',
        'views/jenis_tkp_views.xml',
        'views/menu.xml',
    ],
    'assets': {
         'web.assets_backend': [
            'petadigi/static/lib/leaflet/leaflet.css',
            'petadigi/static/lib/leaflet/leaflet.js',
            'petadigi/static/lib/leaflet/leaflet.editable.js',
            'petadigi/static/src/js/kabupaten_map_widget.js',
            'petadigi/static/src/xml/geojson_map_widget.xml',
            'petadigi/static/src/css/backend.css',
            'petadigi/static/src/css/kabupaten_map_widget.css',
            
        ],
    },
    'installable': True,
    'application': True,
    'sequence': 1,
}