from . import polres
from . import polsek
from . import kabupaten
from . import kecamatan
from . import desa
from . import sumber_dokumen
from . import kategori_kriminal
from . import sub_kategori_kriminal
from . import kategori_bencana
from . import kategori_kamtibmas
from . import kategori_lalu_lintas
from . import kategori_lokasi
from . import jenis_jalan
from . import modus_operandi
from . import jenis_tkp
from . import subdit
from . import kriminalitas
from . import sub_status_perkara
from . import kasus_menonjol
from . import tindak_lanjut
from . import bencana
from . import lalu_lintas
from . import strong_point
from . import lokasi_penting
from . import kategori_sumur_minyak
from . import sumur_minyak
from . import jenis_laporan
from . import hasil_giat
from . import lokasi_strong_point
from . import personel
from . import res_users