from . import polres
from . import polsek
from . import kabupaten
from . import kecamatan
from . import desa
from . import sumber_dokumen
from . import kategori_kriminal
from . import sub_kategori_kriminal
from . import kategori_bencana
from . import kategori_kamtibmas
from . import kategori_lalu_lintas
from . import kategori_lokasi
from . import jenis_jalan
from . import modus_operandi
from . import jenis_tkp
from . import subdit
from . import dashboard